---
type: showroom

# Set the left column width to 30%
default_width: 40
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

tabs:

  - name: OpenShift Console
    url: 'https://console-openshift-console.${DOMAIN}'

  # Horizontal split terminals
  - name: Terminal 1
    path: /terminal
    port: 443
    secondary_name: Terminal 2
    secondary_path: /terminal
    secondary_port: 443

  # Vertical split terminals
  # - name: Terminal 1
  #   path: /terminal/
  #   port: 443
  # - name: Terminal 2
  #   path: /terminal/
  #   port: 443

    # - name: Gitea
#   url: 'https://gitea.${DOMAIN}'
#  - name: LibreChat
#   url: 'https://librechat-librechat-${USER}.${DOMAIN}'
